wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-06
batch_size:
  desc: null
  value: 128
architecture:
  desc: null
  value: KoBERT
dataset:
  desc: null
  value: Naver Sentiment Movie Corpus
epochs:
  desc: null
  value: 10
portion:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696577442.008885
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.15.11
      6: 4.34.0
      8:
      - 5
      13: linux-x86_64
